# Generated by Django 5.1 on 2024-08-10 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='about',
            new_name='description',
        ),
    ]
